package py.edu.ucom.taller1.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CategoriaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaAllPropertiesEquals(Categoria expected, Categoria actual) {
        assertCategoriaAutoGeneratedPropertiesEquals(expected, actual);
        assertCategoriaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaAllUpdatablePropertiesEquals(Categoria expected, Categoria actual) {
        assertCategoriaUpdatableFieldsEquals(expected, actual);
        assertCategoriaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaAutoGeneratedPropertiesEquals(Categoria expected, Categoria actual) {
        assertThat(actual)
            .as("Verify Categoria auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaUpdatableFieldsEquals(Categoria expected, Categoria actual) {
        assertThat(actual)
            .as("Verify Categoria relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()))
            .satisfies(a -> assertThat(a.getFechaModificacion()).as("check fechaModificacion").isEqualTo(expected.getFechaModificacion()))
            .satisfies(a -> assertThat(a.getUsuarioCreacion()).as("check usuarioCreacion").isEqualTo(expected.getUsuarioCreacion()))
            .satisfies(a ->
                assertThat(a.getUsuarioModificacion()).as("check usuarioModificacion").isEqualTo(expected.getUsuarioModificacion())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaUpdatableRelationshipsEquals(Categoria expected, Categoria actual) {
        // empty method
    }
}
