package py.edu.ucom.taller1.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LocalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocalAllPropertiesEquals(Local expected, Local actual) {
        assertLocalAutoGeneratedPropertiesEquals(expected, actual);
        assertLocalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocalAllUpdatablePropertiesEquals(Local expected, Local actual) {
        assertLocalUpdatableFieldsEquals(expected, actual);
        assertLocalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocalAutoGeneratedPropertiesEquals(Local expected, Local actual) {
        assertThat(actual)
            .as("Verify Local auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocalUpdatableFieldsEquals(Local expected, Local actual) {
        assertThat(actual)
            .as("Verify Local relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getUbicacion()).as("check ubicacion").isEqualTo(expected.getUbicacion()))
            .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()))
            .satisfies(a -> assertThat(a.getFechaModificacion()).as("check fechaModificacion").isEqualTo(expected.getFechaModificacion()))
            .satisfies(a -> assertThat(a.getUsuarioCreacion()).as("check usuarioCreacion").isEqualTo(expected.getUsuarioCreacion()))
            .satisfies(a ->
                assertThat(a.getUsuarioModificacion()).as("check usuarioModificacion").isEqualTo(expected.getUsuarioModificacion())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocalUpdatableRelationshipsEquals(Local expected, Local actual) {
        // empty method
    }
}
