package py.edu.ucom.taller1.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static py.edu.ucom.taller1.domain.AssertUtils.bigDecimalCompareTo;

public class MovimientoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovimientoAllPropertiesEquals(Movimiento expected, Movimiento actual) {
        assertMovimientoAutoGeneratedPropertiesEquals(expected, actual);
        assertMovimientoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovimientoAllUpdatablePropertiesEquals(Movimiento expected, Movimiento actual) {
        assertMovimientoUpdatableFieldsEquals(expected, actual);
        assertMovimientoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovimientoAutoGeneratedPropertiesEquals(Movimiento expected, Movimiento actual) {
        assertThat(actual)
            .as("Verify Movimiento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovimientoUpdatableFieldsEquals(Movimiento expected, Movimiento actual) {
        assertThat(actual)
            .as("Verify Movimiento relevant properties")
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a ->
                assertThat(a.getCantidad()).as("check cantidad").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getCantidad())
            )
            .satisfies(a -> assertThat(a.getReferencia()).as("check referencia").isEqualTo(expected.getReferencia()))
            .satisfies(a -> assertThat(a.getFechaMovimiento()).as("check fechaMovimiento").isEqualTo(expected.getFechaMovimiento()))
            .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()))
            .satisfies(a -> assertThat(a.getFechaModificacion()).as("check fechaModificacion").isEqualTo(expected.getFechaModificacion()))
            .satisfies(a -> assertThat(a.getUsuarioCreacion()).as("check usuarioCreacion").isEqualTo(expected.getUsuarioCreacion()))
            .satisfies(a ->
                assertThat(a.getUsuarioModificacion()).as("check usuarioModificacion").isEqualTo(expected.getUsuarioModificacion())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMovimientoUpdatableRelationshipsEquals(Movimiento expected, Movimiento actual) {
        assertThat(actual)
            .as("Verify Movimiento relationships")
            .satisfies(a -> assertThat(a.getProducto()).as("check producto").isEqualTo(expected.getProducto()))
            .satisfies(a -> assertThat(a.getLocalOrigen()).as("check localOrigen").isEqualTo(expected.getLocalOrigen()))
            .satisfies(a -> assertThat(a.getLocalDestino()).as("check localDestino").isEqualTo(expected.getLocalDestino()));
    }
}
