package py.edu.ucom.taller1.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static py.edu.ucom.taller1.domain.AssertUtils.bigDecimalCompareTo;

public class ProductoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductoAllPropertiesEquals(Producto expected, Producto actual) {
        assertProductoAutoGeneratedPropertiesEquals(expected, actual);
        assertProductoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductoAllUpdatablePropertiesEquals(Producto expected, Producto actual) {
        assertProductoUpdatableFieldsEquals(expected, actual);
        assertProductoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductoAutoGeneratedPropertiesEquals(Producto expected, Producto actual) {
        assertThat(actual)
            .as("Verify Producto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductoUpdatableFieldsEquals(Producto expected, Producto actual) {
        assertThat(actual)
            .as("Verify Producto relevant properties")
            .satisfies(a -> assertThat(a.getSku()).as("check sku").isEqualTo(expected.getSku()))
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a ->
                assertThat(a.getPesoPorUnidadKg())
                    .as("check pesoPorUnidadKg")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPesoPorUnidadKg())
            )
            .satisfies(a ->
                assertThat(a.getVolumenPorUnidadL())
                    .as("check volumenPorUnidadL")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getVolumenPorUnidadL())
            )
            .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()))
            .satisfies(a -> assertThat(a.getFechaModificacion()).as("check fechaModificacion").isEqualTo(expected.getFechaModificacion()))
            .satisfies(a -> assertThat(a.getUsuarioCreacion()).as("check usuarioCreacion").isEqualTo(expected.getUsuarioCreacion()))
            .satisfies(a ->
                assertThat(a.getUsuarioModificacion()).as("check usuarioModificacion").isEqualTo(expected.getUsuarioModificacion())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductoUpdatableRelationshipsEquals(Producto expected, Producto actual) {
        assertThat(actual)
            .as("Verify Producto relationships")
            .satisfies(a -> assertThat(a.getUnidadMedida()).as("check unidadMedida").isEqualTo(expected.getUnidadMedida()))
            .satisfies(a -> assertThat(a.getCategoria()).as("check categoria").isEqualTo(expected.getCategoria()));
    }
}
