package py.edu.ucom.taller1.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UnidadMedidaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnidadMedidaAllPropertiesEquals(UnidadMedida expected, UnidadMedida actual) {
        assertUnidadMedidaAutoGeneratedPropertiesEquals(expected, actual);
        assertUnidadMedidaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnidadMedidaAllUpdatablePropertiesEquals(UnidadMedida expected, UnidadMedida actual) {
        assertUnidadMedidaUpdatableFieldsEquals(expected, actual);
        assertUnidadMedidaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnidadMedidaAutoGeneratedPropertiesEquals(UnidadMedida expected, UnidadMedida actual) {
        assertThat(actual)
            .as("Verify UnidadMedida auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnidadMedidaUpdatableFieldsEquals(UnidadMedida expected, UnidadMedida actual) {
        assertThat(actual)
            .as("Verify UnidadMedida relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDimension()).as("check dimension").isEqualTo(expected.getDimension()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUnidadMedidaUpdatableRelationshipsEquals(UnidadMedida expected, UnidadMedida actual) {
        // empty method
    }
}
